### ISSUE TITLE
CustomError update not reflected in latest version

### ISSUE THREAD

**Issue by terran6** [CosmWasm/cw-template#137]
There have been various updates to the CustomError as per the following link:
https://github.com/CosmWasm/cw-template/commit/3a5bda859d75222c54338cb389937fc486f315c7

It would be nice to have this reflected in a current version of the CosmWasm/cw-template.  Thank you!

**Comment by uint** [comment]
I'm not sure I understand. Is this a request to tag a new version of `cw-template`?

**Comment by terran6** [comment]
Yup! Tagging a new version to reflect the changes would be helpful. 👍🏼

**Comment by webmaster128** [comment]
What do you need the version for? We never really used versions here. Can't you just generate from main as described on the main README?

```
cargo generate --git https://github.com/CosmWasm/cw-template.git --name PROJECT_NAME
```

**Comment by terran6** [comment]
I found a workaround just working off of a git hash for a particular commit which should work fine for me.  Thanks for your help.
