### ISSUE TITLE
Install issue - error: failed to run custom build command for `openssl-sys v0.9.80`

### ISSUE THREAD

**Issue by MetehanUnal00** [CosmWasm/cw-template#144]
This is probably not the place for this but in case someone else also encounters this error I will try to solve it and share the results here. When I run 
`cargo install cargo-generate --features vendored-openssl`
I get:

Caused by:
  process didn't exit successfully: `C:\Users\PC\AppData\Local\Temp\cargo-installD3wUvn\release\build\openssl-sys-a7c49c2d5741077c\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rustc-cfg=openssl
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  running "perl" "./Configure" "--prefix=C:\\Users\\PC\\AppData\\Local\\Temp\\cargo-installD3wUvn\\release\\build\\openssl-sys-02ecb9bfd246b8a5\\out\\openssl-build\\install" "--openssldir=SYS$MANAGER:[OPENSSL]" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-engine" "no-asm" "VC-WIN64A"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', C:\Users\PC\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-src-111.25.0+1.1.1t\src\lib.rs:497:39
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-generate v0.17.6`, intermediate artifacts can be found at `C:\Users\PC\AppData\Local\Temp\cargo-installD3wUvn`

What I tried so far is:
1- Installing strawberry perl. Didn't work.
2- [This](https://stackoverflow.com/a/62729715/12398385)
3- [This](https://stackoverflow.com/a/66197124/12398385)
Still trying to solve it.

**Comment by Barbaros241** [comment]
Since I was battling with this error for approximately 2 hours I forgot to add somethings:
1- I ran win10 machine.
2- Before 
> Caused by: 

there is one more line:
error: failed to run custom build command for `openssl-sys v0.9.80`

**Comment by MetehanUnal00** [comment]
Works like a charm in ubuntu. Also if I just bypass the problematic line it works in windows too. So I guess it is solved.
