### ISSUE TITLE
deploy.sh not created

### ISSUE THREAD

**Issue by SteveMBao** [CosmWasm/cw-template#147]
Hello admin, I'm using https://docs.sei.io/develop/get-started/counter-smart-contract-tutorial guide to build my first contract (step by step), but `docker run --rm -v "$(pwd)":/code --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry cosmwasm/rust-optimizer:0.12.11` not created deploy.sh file, 
![image](https://github.com/CosmWasm/cw-template/assets/17777077/5e1bff44-216a-4335-b176-809c3ae9188d)
![image](https://github.com/CosmWasm/cw-template/assets/17777077/98b4463e-f3d7-419a-bc9e-4df864a38a94)
could someone help me to fix it?

**Comment by webmaster128** [comment]
deploy.sh is something Sei specific I don't know about.

From the original tutorial:

> Then create a new file called deploy.sh
> ...
> Paste the following code into deploy.sh

**Comment by memilis007** [comment]
Yes
