### ISSUE TITLE
Rename cosmwasm-template to cw-template

### ISSUE THREAD

**Issue by ueco-jb** [CosmWasm/cw-template#83]
https://github.com/CosmWasm/cw-plus/pull/411#discussion_r705971051
Same case as with `s/cosmwasm-plus/cw-plus/g` transition

**Comment by ethanfrey** [comment]
Thanks for bringing this up.

We also need to rename the cosmwasm-plus branch to cw-plus. (And update it to be useful again)

**Comment by ethanfrey** [comment]
I did the GitHub rename, but this issue still stands to update all the references in the repo.
