### ISSUE TITLE
Deploying smart contract from template fails due to an unknown interface version

### ISSUE THREAD

**Issue by ezekiiel** [CosmWasm/cw-template#94]
Following the [deployment example](https://docs.cosmwasm.com/docs/0.16/getting-started/interact-with-contract) from the documentation deploying the smart contract generated by this template fails:

```
Error: rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract has unknown interface_version_* marker export (see https://github.com/CosmWasm/cosmwasm/blob/main/packages/vm/README.md): create wasm contract failed: invalid request
```

It seems like this starts with [this](https://github.com/CosmWasm/cw-template/commit/7de3f1dd900fad7e65e31f2b61a0f42112244f5f) commit which upgrades the `cosmwasm-std` version to `1.0.0-beta`. Rolling the dependencies back to:

```
cosmwasm-std = { version = "0.16" }
cosmwasm-storage = { version = "0.16" }
cw-storage-plus = "0.9"
cw2 = "0.9"
```

Appears to resolve the issue.

**Comment by ethanfrey** [comment]
This is for Terra.
Terra uses 0.16.
The main branch targets latest cosmwasm 1.0.0-beta as it should.

Please follow the Readme and use `--branch 0.16` which is what Terra uses.

If you want to make a pr to the Readme saying this, I'd merge it

**Comment by ethanfrey** [comment]
This is a docs issue actually...

https://docs.cosmwasm.com/docs/0.16/getting-started/installation refers to wasmd 0.18!

We need to either explicitly refer to the old branch in those docs, or update docs to use wasmd 0.20, which is 1.0-beta.

@orkunkl can you take a hand on this?

**Comment by sp41mer** [comment]
Hi @ethanfrey 

I have the following issue for 0.18.0 version of wasmd and for 0.20.0-18-g14e58bf as well

I followed steps from this docs: https://docs.cosmwasm.com/dev-academy/develop-smart-contract/intro#start-with-a-template

But when I make `RES=$(wasmd tx wasm store artifacts/my_first_contract.wasm --from wallet $TXFLAG -y)`, I have the following issue: 
```
Error: rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract has unknown interface_version_* marker export (see https://github.com/CosmWasm/cosmwasm/blob/main/packages/vm/README.md): create wasm contract failed: invalid request
```

**Comment by orkunkl** [comment]
@sp41mer still looks like version mismatch, we release CosmWasm docs 1.0 https://docs.cosmwasm.com/docs/1.0. You can use uni juno testnet for testing with cosmwasm version 1.0

**Comment by orkunkl** [comment]
@ezekiiel can you close the issue after you verify it is resolved?

**Comment by ezekiiel** [comment]
Recently did this [here](https://github.com/ezekiiel/item-dao) and it all worked fine out of the box. Seems good to me :) Thanks!

**Comment by taitruong** [comment]
Still having this issue. Followed steps described in the docs here: https://docs.terra.money/docs/develop/guides/smart-contracts/write-smart-contract.html

As stated in docs it refers to branch 0.16:
> cargo generate --git https://github.com/CosmWasm/cw-template.git --branch 0.16 --name my-first-contract
cd my-first-contract

But when deploying to localterra I get this error:
> $ terrad tx wasm store artifacts/my_first_contract.wasm --from test1 --chain-id=localterra --gas=auto --fees=100000uluna --broadcast-mode=block
Error: rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract has unknown interface_version_* marker export (see https://github.com/CosmWasm/cosmwasm/blob/main/packages/vm/README.md): create wasm contract failed: invalid request

**Comment by orkunkl** [comment]
@taitruong probably localterra cw vm version and contract cw version do not match

**Comment by taitruong** [comment]
@orkunkl in which file can I check which version localterra is using?
