### ISSUE TITLE
cargo run-script optimize "spurious network error"

### ISSUE THREAD

**Issue by ColtraneNadler** [CosmWasm/cw-template#97]
When running
`cargo run-script optimize`

I get the error

```
Cache size                            0 bytes
Max cache size                       10 GiB
Building contract in /code ...
    Updating crates.io index
warning: spurious network error (2 tries remaining): failed to resolve address for github.com: Name does not resolve; class=Net (12)
warning: spurious network error (1 tries remaining): failed to resolve address for github.com: Name does not resolve; class=Net (12)
error: failed to get `cosmwasm-std` as a dependency of package `template v0.1.0 (/code)`
```

I checked in a different docker container, and I can access the internet from within the container... so not sure what's happening here.

Any ideas for how to solve this so I can build my contracts?

**Comment by webmaster128** [comment]
Github has mjor availability issues last night. https://www.githubstatus.com/incidents/r5qrpp2f5fc0 Could you check if it is resolved now?
